package:
  name: chira
  version: 1.1.0

source:
  git:url: https://github.com/pavanvidem/chira
  git_rev: 4686b4b34f34455417e68addc1ba63341b187517

build:
  number: 1
  skip: True  # [osx]

requirements:
  host:
    - python
  run:
    - python
    - pysam >=0.15.0
    - bcbiogff >= 0.6.6
    - biopython >= 1.70

test:
  commands:
    - python chira.py -h 2>&1 | grep Chimeric

about:
  home: https://github.com/pavanvidem/chira
  license: GPL
  license_file: LICENSE
  summary: An integrated framework for annotation and visualization of chimeric reads.
